# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-10 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160810_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='image',
            field=models.ImageField(height_field='150', max_length=255, upload_to='images/', width_field='150'),
        ),
    ]
