# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-11 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160811_1207'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('id', 'network')]),
        ),
    ]
