# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160811_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='endDate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='startDate',
            new_name='startdate',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='releaseDate',
            new_name='releasedate',
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('resume', 'network')]),
        ),
    ]
