# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoimage',
            name='attribution',
            field=models.TextField(blank=True),
        ),
    ]
