# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_logoimage_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoimage',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
