# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20160816_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='logoimage',
            name='alt_image',
            field=models.ImageField(max_length=50, null=True, upload_to='images/logos/'),
        ),
    ]
