# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_logoimage_alt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoimage',
            name='alt_image',
            field=models.ImageField(blank=True, max_length=50, null=True, upload_to='images/logos/'),
        ),
    ]
