# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_resume_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('image', models.URLField()),
                ('alt_image', models.URLField(blank=True, null=True)),
                ('attribution', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LogoImage',
        ),
    ]
