# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20160827_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-startDate']},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-releaseDate']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-startDate']},
        ),
        migrations.RenameField(
            model_name='education',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='startdate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='releasedate',
            new_name='releaseDate',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='enddate',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='startdate',
            new_name='startDate',
        ),
    ]
