# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20160831_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='studytype',
            new_name='studyType',
        ),
    ]
